# Generated by Django 6.0.6 on 2026-07-05 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        ('projects', '0002_alter_project_options_project_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiplan',
            name='generated_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiplan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='projects.project'),
        ),
    ]
