# Generated by Django 6.0.6 on 2026-07-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_aiplan_generated_images_alter_aiplan_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiplan',
            name='drawing_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiplan',
            name='saved_drawing_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiplan',
            name='temporary_drawing_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiplan',
            name='temporary_drawing_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
